# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Victor Challier
description: > # this means to ignore newlines until "baseurl:"
  I write about Data Sciences, Python, Algorithms & Data Structures. New interview problems and solutions posted every week!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://challier.github.io/home" # the base hostname & protocol for your site
permalink: "/:title/"
CNAME: "victor.data.com"

# Contact settings
email: challier.victor@gmail.com
twitter_username: victor_challier
github_username:  challier-08

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

gems:
  - jekyll-sitemap

exclude: ["README.md", "LICENSE.md", "screenshot.png"]
